import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.scss";
import { Button } from "react-bootstrap";
import Header from "@/components/siteComponents/header/Header";
import { useState,ChangeEvent } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [file, setFile] = useState<File>();
  const [responseData, setResponseData] = useState("");

  const handleFileChange = (e: ChangeEvent<HTMLInputElement>) => {
    if (e.target.files) {
      setFile(e.target.files[0]);
    }
  };

  const handleUploadClick = () => {
    if (!file) {
      return;
    }

    // 👇 Uploading the file using the fetch API to the server
    fetch('https://aiquizmaster.app/backend/doc', {
      method: 'POST',
      body: file,
      // 👇 Set headers manually for single file upload
      headers: {
        'content-type': file.type,
        'content-length': `${file.size}`, // 👈 Headers need to be a string
      },
    })
      .then((res) => res.json())
      .then((data) => {console.log(data);
        setResponseData(data);
      })
      .catch((err) => console.error(err));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
      <div className={styles.description}>
        <Header/>
        </div>
        {/* <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>pages/index.tsx</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer"
            >
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div> */}

        <div className="card p-4 my-5 container">
        
            <h1 className="text-dark text-center fw-bold ">Select & Upload</h1>
         
          <br />
          <form encType="multipart/form-data" className="text-dark">
          <span>{file && `${file.name} - ${file.type}`}</span>
            <input type="file" name="filearg" onChange={handleFileChange} />
            <br />
            <br />
            <div className="text-center py-3">
            <Button  className="text-center form-control" variant="primary" onClick={handleUploadClick}>upload</Button>
            {responseData?<span>Response:responseData</span>:""}
            </div>
           
          </form>
        </div>

       
      </main>
    </>
  );
}
